In [1]:
# Program 1

from numpy import *
from sympy import Matrix

A = [[4, 3, 2], [1, 4, 1], [3, 10, 4]]

print("The given matrix A is")

display(Matrix(A))
eig_val, eig_vec = linalg.eig(A) # Computes the eigenvalues and eigenvectors of a square matrix


print("Eigen values: \n", eig_val)
print("Eigen Values: \n", eig_vec)

The given matrix A is


Matrix([
[4,  3, 2],
[1,  4, 1],
[3, 10, 4]])

Eigen values: 
 [8.98205672 2.12891771 0.88902557]
Eigen Values: 
 [[-0.49247712 -0.82039552 -0.42973429]
 [-0.26523242  0.14250681 -0.14817858]
 [-0.82892584  0.55375355  0.89071407]]


In [2]:
# Exercise 1

from numpy import *
from sympy import Matrix

A = [[25, 1, 2], [1, 3, 0], [2, 0, -4]]

print("The given matrix A is")
display(Matrix(A))
eig_val, eig_vec = linalg.eig(A)
print("Eigen values: \n", eig_val)
print("Eigen Values: \n", eig_vec)

The given matrix A is


Matrix([
[25, 1,  2],
[ 1, 3,  0],
[ 2, 0, -4]])

Eigen values: 
 [25.18215138 -4.13794129  2.95578991]
Eigen Values: 
 [[ 0.9966522   0.06880398  0.04416339]
 [ 0.04493037 -0.00963919 -0.99894362]
 [ 0.0683056  -0.99758363  0.01269831]]


In [3]:
# Program 2

from numpy import *
A = [[25, 1, 2], [1, 3, 0], [2, 0, -4]]
X = [1, 0, 0] #  Initial guess for the eigenvector
λ_i = 0 # Tracks the eigenvalue from the previous iteration (initialized to 0)

while(True):

  Y = dot(A, X) # Multiplies A with the current eigenvector estimate X to get a new vector Y
  λ = abs(Y).max() # Takes the maximum absolute value in Y as an approximation of the dominant eigenvalue
  X = Y/λ # Normalizes the vector Y to avoid numerical overflow or underflow and prepares it for the next iteration

  print("\nThe largest Eigenvalue is: %.4f"%λ)
  print("\nCorresponding Eigenvector is: ", X.round(decimals = 4))

  if abs(λ - λ_i) < 0.001:
    break
  else:
    λ_i = λ

print("\nThe solution is:\n")
print("The largest EigenValue is: %.4f"%λ)
print("Corresponding EigenVector is: ", X.round(decimals = 4))



The largest Eigenvalue is: 25.0000

Corresponding Eigenvector is:  [1.   0.04 0.08]

The largest Eigenvalue is: 25.2000

Corresponding Eigenvector is:  [1.     0.0444 0.0667]

The largest Eigenvalue is: 25.1778

Corresponding Eigenvector is:  [1.     0.045  0.0688]

The largest Eigenvalue is: 25.1827

Corresponding Eigenvector is:  [1.     0.0451 0.0685]

The largest Eigenvalue is: 25.1820

Corresponding Eigenvector is:  [1.     0.0451 0.0685]

The solution is:

The largest EigenValue is: 25.1820
Corresponding EigenVector isL  [1.     0.0451 0.0685]


In [4]:
# Exercise 2

from numpy import *
A = [[6, 1, 2], [1, 10, -1], [2, 1, -4]]
X = [1, 0, 0]
λ_i = 0

while(True):
  Y = dot(A, X)
  λ = abs(Y).max()
  X = Y/λ
  print("\nThe largest Eigenvalue is: %.4f"%λ)
  print("\nCorresponding Eigenvector is: ", X.round(decimals = 4))
  if abs(λ - λ_i) < 0.001:
    break
  else:
    λ_i = λ

print("\nThe solution is:\n")
print("The largest EigenValue is: %.4f"%λ)
print("Corresponding EigenVector is: ", X.round(decimals = 4))



The largest Eigenvalue is: 6.0000

Corresponding Eigenvector is:  [1.     0.1667 0.3333]

The largest Eigenvalue is: 6.8333

Corresponding Eigenvector is:  [1.     0.3415 0.122 ]

The largest Eigenvalue is: 6.5854

Corresponding Eigenvector is:  [1.     0.6519 0.2815]

The largest Eigenvalue is: 7.2370

Corresponding Eigenvector is:  [0.9969 1.     0.2108]

The largest Eigenvalue is: 10.7861

Corresponding Eigenvector is:  [0.6864 1.     0.1994]

The largest Eigenvalue is: 10.4870

Corresponding Eigenvector is:  [0.5261 1.     0.1502]

The largest Eigenvalue is: 10.3759

Corresponding Eigenvector is:  [0.4295 1.     0.1399]

The largest Eigenvalue is: 10.2897

Corresponding Eigenvector is:  [0.3748 1.     0.1263]

The largest Eigenvalue is: 10.2485

Corresponding Eigenvector is:  [0.3417 1.     0.1214]

The largest Eigenvalue is: 10.2202

Corresponding Eigenvector is:  [0.3222 1.     0.1172]

The largest Eigenvalue is: 10.2050

Corresponding Eigenvector is:  [0.3104 1.     0.1152]

Th